# Generated by Django 5.1.1 on 2024-11-26 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines_info', '0002_disciplina_ementa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='estilo_aula',
        ),
        migrations.RemoveField(
            model_name='review',
            name='presenca',
        ),
        migrations.AddField(
            model_name='review',
            name='experiencia',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
